# Generated by Django 4.0.5 on 2022-06-17 13:55

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryType', models.CharField(choices=[('TN', 'Tanks'), ('HL', 'Healers'), ('DD', 'DD'), ('MR', 'Merchants'), ('GM', 'Guild Masters'), ('QG', 'Quest Givers'), ('BS', 'Blacksmiths'), ('TA', 'Tanners'), ('PM', 'Potion Makers'), ('SM', 'Spell Masters')], default='TN', max_length=2, verbose_name='Type category')),
                ('dateCreation', models.DateTimeField(auto_now_add=True, verbose_name='Date Creation')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Ad',
                'verbose_name_plural': 'Ads',
                'ordering': ('dateCreation',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreation', models.DateTimeField(auto_now_add=True, verbose_name='Date Creation')),
                ('text', models.TextField(verbose_name='Text')),
                ('status_remove', models.BooleanField(default=False, verbose_name='Отклик - отклонен')),
                ('status_add', models.BooleanField(default=False, verbose_name='Отклик - принят')),
                ('commentAd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.ad')),
                ('commentUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ('dateCreation',),
            },
        ),
    ]
