# Generated by Django 4.1.7 on 2023-04-07 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_num_car', models.CharField(max_length=255, unique=True, verbose_name='Зав. № машины')),
                ('factory_num_motor', models.CharField(max_length=255, verbose_name='Зав. № двигателя')),
                ('factory_num_transmissions', models.CharField(max_length=255, verbose_name='Зав. № трансмиссии')),
                ('factory_num_driving_bridge', models.CharField(max_length=255, verbose_name='Зав. № ведущего моста')),
                ('factory_num_controlled_bridge', models.CharField(max_length=255, verbose_name='Зав. № управляемого моста')),
                ('contract_num_data', models.CharField(max_length=255, verbose_name='Договор поставки №, дата')),
                ('ship_date', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('consignee', models.CharField(max_length=255, verbose_name='Грузополучатель (конечный потребитель)')),
                ('delivery_address', models.CharField(max_length=255, verbose_name='Адрес поставки (эксплуатации)')),
                ('equipment', models.CharField(max_length=255, verbose_name='Комплектация (доп. опции)')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
                'ordering': ['factory_num_car'],
            },
        ),
        migrations.CreateModel(
            name='ModelControlledBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель управляемого моста',
                'verbose_name_plural': 'Модели управляемого моста',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ModelDrivingBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель ведущего моста',
                'verbose_name_plural': 'Модели ведущего моста',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ModelMotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель двигателя',
                'verbose_name_plural': 'Модели двигателей',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ModelTechnics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель техники',
                'verbose_name_plural': 'Модель техники',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ModelTransmissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель трансмиссии',
                'verbose_name_plural': 'Модели трансмиссии',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Способ восстановления',
                'verbose_name_plural': 'Способы восстановления',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TypeFault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Характер отказа',
                'verbose_name_plural': 'Характер отказа',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TypeMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вид ТО',
                'verbose_name_plural': 'Вид ТО',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('title', models.ForeignKey(limit_choices_to=models.Q(('groups__name', 'Service company')), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Логин')),
            ],
            options={
                'verbose_name': 'Сервисная компания',
                'verbose_name_plural': 'Сервисные компании',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_maintenance', models.DateField(verbose_name='Дата проведения ТО')),
                ('operating_time', models.IntegerField(verbose_name='Наработка, м/час')),
                ('num_order', models.CharField(max_length=255, unique=True, verbose_name='№ заказ-наряда')),
                ('data_order', models.DateField(verbose_name='Дата заказ-наряда')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.car', verbose_name='Машина')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.servicecompany', verbose_name='Сервисная компания')),
                ('type_maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.typemaintenance', verbose_name='Вид ТО')),
            ],
            options={
                'verbose_name': 'Техническое обслуживание',
                'verbose_name_plural': 'Технические обслуживания',
                'ordering': ['data_order'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('title', models.ForeignKey(limit_choices_to=models.Q(('groups__name', 'Clients')), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Логин')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_rejection', models.DateTimeField(verbose_name='Дата заказ-наряда')),
                ('operating_time', models.IntegerField(verbose_name='Наработка, м/час')),
                ('description_failure', models.TextField(verbose_name='Описание отказа')),
                ('spare_parts', models.TextField(verbose_name='Используемые запасные части')),
                ('data_restoration', models.DateTimeField(blank=True, null=True, verbose_name='Дата восстановления')),
                ('downtime_technic', models.TextField(blank=True, null=True, verbose_name='Время простоя')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.car', verbose_name='Машина')),
                ('node_failure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.typefault', verbose_name='Узел отказа')),
                ('recovery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.recoverymethod', verbose_name='Способ восстановления')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.servicecompany', verbose_name='Сервисная компания')),
            ],
            options={
                'verbose_name': 'Рекламация',
                'verbose_name_plural': 'Рекламации',
                'ordering': ['data_rejection'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_controlled_bridge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.modelcontrolledbridge', verbose_name='Модель управляемого моста'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_driving_bridge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.modeldrivingbridge', verbose_name='Модель ведущего моста'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_motor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.modelmotor', verbose_name='Модель двигателя'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_technics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.modeltechnics', verbose_name='Модель техники'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_transmissions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.modeltransmissions', verbose_name='Модель трансмиссии'),
        ),
        migrations.AddField(
            model_name='car',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.servicecompany', verbose_name='Сервисная компания'),
        ),
    ]
