# Generated by Django 4.1.7 on 2023-04-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='description',
            field=models.TextField(blank=True, default='описания нет', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='modelcontrolledbridge',
            name='description',
            field=models.TextField(blank=True, default='описания нет', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='modeldrivingbridge',
            name='description',
            field=models.TextField(blank=True, default='описания нет', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='modelmotor',
            name='description',
            field=models.TextField(blank=True, default='описания нет', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='modeltechnics',
            name='description',
            field=models.TextField(blank=True, default='описания нет', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='modeltransmissions',
            name='description',
            field=models.TextField(blank=True, default='описания нет', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='recoverymethod',
            name='description',
            field=models.TextField(blank=True, default='описания нет', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='servicecompany',
            name='description',
            field=models.TextField(blank=True, default='описания нет', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='typefault',
            name='description',
            field=models.TextField(blank=True, default='описания нет', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='typemaintenance',
            name='description',
            field=models.TextField(blank=True, default='описания нет', null=True, verbose_name='Описание'),
        ),
    ]
